# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class ToolApprovalPolicyAction(UncheckedBaseModel):
    expire_at_timestamp_seconds: typing.Optional[int] = pydantic.Field(default=None)
    """
    Unix timestamp (seconds) when this session allow expires. Omit to allow for the whole session.
    """

    status: typing.Literal["allow_session"] = pydantic.Field(default="allow_session")
    """
    Allow matching tool calls for the rest of this session.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
