# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .tool_approval_policy_item import ToolApprovalPolicyItem


class UserToolApprovalPolicyEvent(UncheckedBaseModel):
    policies: typing.List[ToolApprovalPolicyItem] = pydantic.Field()
    """
    One or more (server, tool_name) policy entries.
    """

    thread_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Null when session-scoped; set when delivered against a tip thread.
    """

    type: typing.Literal["user.tool_approval_policy"] = pydantic.Field(default="user.tool_approval_policy")
    """
    Sticky allow-session policy for matching tools (optional expiry).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
