// This file was auto-generated by Fern from our API Definition.

export interface ToolApprovalPolicyAction {
    /** Unix timestamp (seconds) when this session allow expires. Omit to allow for the whole session. */
    expireAtTimestampSeconds?: number;
    /** Allow matching tool calls for the rest of this session. */
    status: "allow_session";
}
