// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface UserToolApprovalPolicyEvent {
    /** One or more (server, tool_name) policy entries. */
    policies: TrueForge.ToolApprovalPolicyItem[];
    /** Null when session-scoped; set when delivered against a tip thread. */
    threadId: string | null;
    /** Sticky allow-session policy for matching tools (optional expiry). */
    type: "user.tool_approval_policy";
}
