// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface UserToolApprovalPolicyStreamEvent extends TrueForge.UserToolApprovalPolicyEvent {
    /** ISO 8601 event timestamp. */
    createdAt: string;
    /** Unique identifier for the event (monotonic ULID). */
    id: string;
}
