// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ToolApprovalPolicyAction: core.serialization.ObjectSchema<
    serializers.ToolApprovalPolicyAction.Raw,
    TrueForge.ToolApprovalPolicyAction
> = core.serialization.object({
    expireAtTimestampSeconds: core.serialization.property(
        "expire_at_timestamp_seconds",
        core.serialization.number().optional(),
    ),
    status: core.serialization.stringLiteral("allow_session"),
});

export declare namespace ToolApprovalPolicyAction {
    export interface Raw {
        expire_at_timestamp_seconds?: number | null;
        status: "allow_session";
    }
}
