// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ToolApprovalPolicyItem } from "./ToolApprovalPolicyItem.js";

export const UserToolApprovalPolicyEvent: core.serialization.ObjectSchema<
    serializers.UserToolApprovalPolicyEvent.Raw,
    TrueForge.UserToolApprovalPolicyEvent
> = core.serialization.object({
    policies: core.serialization.list(ToolApprovalPolicyItem),
    threadId: core.serialization.property("thread_id", core.serialization.string().nullable()),
    type: core.serialization.stringLiteral("user.tool_approval_policy"),
});

export declare namespace UserToolApprovalPolicyEvent {
    export interface Raw {
        policies: ToolApprovalPolicyItem.Raw[];
        thread_id?: string | null;
        type: "user.tool_approval_policy";
    }
}
