// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { UserToolApprovalPolicyEvent } from "./UserToolApprovalPolicyEvent.js";

export const UserToolApprovalPolicyStreamEvent: core.serialization.ObjectSchema<
    serializers.UserToolApprovalPolicyStreamEvent.Raw,
    TrueForge.UserToolApprovalPolicyStreamEvent
> = core.serialization
    .object({
        createdAt: core.serialization.property("created_at", core.serialization.string()),
        id: core.serialization.string(),
    })
    .extend(UserToolApprovalPolicyEvent);

export declare namespace UserToolApprovalPolicyStreamEvent {
    export interface Raw extends UserToolApprovalPolicyEvent.Raw {
        created_at: string;
        id: string;
    }
}
